import { deriveContributorProfiles } from "./contributors.js";
import type { ContributorDisplayOptions } from "./contributors.js";
import { normalizeSafeHttpsUrl } from "./safe-url.js";
import type { ContributorRecognitionProfile, PublicRecognitionSummary } from "./types.js";

const AVATAR_SIZE = 96;

export interface ContributorPageOptions extends ContributorDisplayOptions {
  readonly title?: string;
}

export function renderContributorPage(
  values: readonly unknown[],
  options: ContributorPageOptions = {},
): string {
  const profiles = deriveContributorProfiles(values, options);
  const title = normalizeTitle(options.title, profiles);
  const cards =
    profiles.length === 0
      ? '<p class="empty">No approved recognition records yet.</p>'
      : profiles.map(renderContributorCard).join("\n");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="referrer" content="no-referrer">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src https://avatars.githubusercontent.com; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'">
  <title>${escapeHtml(title)}</title>
  <style>${PAGE_STYLES}</style>
</head>
<body>
  <a class="skip-link" href="#contributors">Skip to contributors</a>
  <header>
    <p class="eyebrow">Maintainer-approved recognition</p>
    <h1>${escapeHtml(title)}</h1>
    <p class="intro">Contribution stories backed by repository evidence. Generated by Clarissimi.</p>
  </header>
  <main id="contributors" class="grid" aria-label="Recognized contributors">
    ${cards}
  </main>
  <footer>Generated from <code>.clarissimi/contributions.jsonl</code>.</footer>
</body>
</html>
`;
}

function renderContributorCard(profile: ContributorRecognitionProfile): string {
  const contributor = profile.contributor;
  const profileUrl = escapeHtmlAttribute(
    normalizeSafeHttpsUrl(contributor.profileUrl, "$.contributor.profileUrl", "HTML"),
  );
  const avatarUrl = escapeHtmlAttribute(
    `https://avatars.githubusercontent.com/u/${encodeURIComponent(contributor.id)}?s=${AVATAR_SIZE}&v=4`,
  );
  const kind = renderContributorKind(contributor.kind);
  const contributionLabel =
    profile.contributionCount === 1
      ? "1 recognized contribution"
      : `${profile.contributionCount} recognized contributions`;
  const types = profile.contributionTypes
    .map((type) => `<span class="type">${escapeHtml(type)}</span>`)
    .join("");
  const recognitions = profile.recognitions.map(renderRecognition).join("\n");

  return `<article class="card">
      <div class="identity">
        <img src="${avatarUrl}" width="${AVATAR_SIZE}" height="${AVATAR_SIZE}" loading="lazy" alt="">
        <div>
          <h2><a href="${profileUrl}">@${escapeHtml(contributor.login)}</a></h2>
          ${kind}
          <p class="count">${contributionLabel}</p>
        </div>
      </div>
      <div class="types" aria-label="Contribution types">${types}</div>
      <ul class="recognitions">${recognitions}</ul>
    </article>`;
}

function renderContributorKind(kind: ContributorRecognitionProfile["contributor"]["kind"]): string {
  if (kind === "bot") {
    return '<span class="kind">Bot</span>';
  }
  if (kind === "ai_agent") {
    return '<span class="kind">AI agent</span>';
  }
  return "";
}

function renderRecognition(recognition: PublicRecognitionSummary): string {
  const evidence = recognition.evidenceRefs.find((candidate) => candidate.url !== undefined);
  const evidenceLink =
    evidence?.url === undefined
      ? ""
      : ` <a class="evidence" href="${escapeHtmlAttribute(
          normalizeSafeHttpsUrl(evidence.url, "$.evidenceRefs[].url", "HTML"),
        )}">${escapeHtml(evidence.title ?? `${evidence.kind} ${evidence.id}`)}</a>`;

  return `<li>
          <p>${escapeHtml(recognition.publicRecognitionText)}</p>
          <p class="meta"><span>${escapeHtml(recognition.affectedArea)}</span><span>${escapeHtml(recognition.suggestedBadge)}</span>${evidenceLink}</p>
        </li>`;
}

function normalizeTitle(
  value: string | undefined,
  profiles: readonly ContributorRecognitionProfile[],
): string {
  const normalized = value?.replace(/\s+/g, " ").trim();
  if (normalized !== undefined && normalized.length > 0) {
    return normalized;
  }

  const repositories = new Set(
    profiles.flatMap((profile) => profile.recognitions.map((entry) => entry.source.repository)),
  );
  const repository = repositories.size === 1 ? repositories.values().next().value : undefined;
  return repository === undefined ? "Contributors" : `${repository} contributors`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function escapeHtmlAttribute(value: string): string {
  return escapeHtml(value);
}

const PAGE_STYLES = `
    :root { color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui, sans-serif; --page: #0d1117; --surface: #161b22; --surface-muted: #21262d; --border: #30363d; --border-strong: #484f58; --text: #f0f6fc; --text-muted: #b1bac4; --text-subtle: #8c959f; --link: #79c0ff; --focus: #f2cc60; --accent: #1f6f3d; --accent-text: #d8fbe4; --automation: #6e40c9; background: var(--page); color: var(--text); }
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; background: var(--page); background: radial-gradient(circle at top, #1f2937 0, var(--page) 42rem); }
    a { color: var(--link); }
    a:focus-visible { outline: 3px solid var(--focus); outline-offset: 3px; }
    .skip-link { position: absolute; left: 1rem; top: -4rem; padding: .75rem 1rem; background: var(--text); color: var(--page); border-radius: .5rem; z-index: 2; }
    .skip-link:focus { top: 1rem; }
    header, main, footer { width: min(72rem, calc(100% - 2rem)); margin-inline: auto; }
    header { padding: 5rem 0 2.5rem; }
    .eyebrow { margin: 0 0 .75rem; color: var(--link); font-size: .82rem; font-weight: 750; letter-spacing: .12em; text-transform: uppercase; }
    h1 { margin: 0; font-size: clamp(2.5rem, 7vw, 5rem); line-height: 1; letter-spacing: -.04em; }
    .intro { max-width: 42rem; margin: 1.25rem 0 0; color: var(--text-muted); font-size: 1.08rem; line-height: 1.65; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 27rem), 1fr)); gap: 1rem; padding-bottom: 3rem; }
    .card { padding: 1.4rem; border: 1px solid var(--border); border-radius: 1rem; background: var(--surface); background: color-mix(in srgb, var(--surface) 94%, transparent); box-shadow: 0 1rem 3rem rgba(0,0,0,.18); }
    .identity { display: flex; gap: 1rem; align-items: center; }
    .identity img { border-radius: 50%; border: 2px solid var(--border); background: var(--surface-muted); }
    h2 { margin: 0 0 .35rem; font-size: 1.25rem; overflow-wrap: anywhere; }
    h2 a { color: inherit; text-decoration-thickness: .08em; text-underline-offset: .18em; }
    .kind, .type, .meta span, .evidence { display: inline-block; margin: .15rem .3rem .15rem 0; padding: .2rem .5rem; border-radius: 999px; font-size: .76rem; }
    .kind { background: var(--automation); color: #fff; }
    .count { margin: .35rem 0 0; color: var(--text-muted); font-size: .9rem; }
    .types { margin: 1rem 0 .4rem; }
    .type { background: var(--accent); color: var(--accent-text); }
    .recognitions { margin: .6rem 0 0; padding-left: 1.2rem; }
    .recognitions li { padding: .7rem 0; }
    .recognitions p { margin: 0; line-height: 1.5; }
    .recognitions .meta { margin-top: .45rem; color: var(--text-subtle); }
    .meta span { border: 1px solid var(--border); }
    .evidence { color: var(--link); }
    .empty { grid-column: 1 / -1; padding: 3rem; border: 1px dashed var(--border-strong); border-radius: 1rem; color: var(--text-muted); text-align: center; }
    footer { padding: 0 0 3rem; color: var(--text-subtle); font-size: .85rem; }
    code { color: var(--text); }
    @media (max-width: 34rem) { header { padding-top: 3rem; } .identity { align-items: flex-start; } .identity img { width: 72px; height: 72px; } .card { padding: 1rem; } }
    @media (prefers-contrast: more) { .card, .meta span { border-color: currentColor; } }
    @media (forced-colors: active) { .card, .identity img, .meta span { border-color: CanvasText; } }
  `;
