import type {
  ContributorRecognitionProfile,
  PublicRecognitionSummary
} from "./types.js";
import { deriveContributorProfiles } from "./contributors.js";

export interface ContributorsMarkdownOptions {
  readonly title?: string;
}

export function renderContributorsMarkdown(
  values: readonly unknown[],
  options: ContributorsMarkdownOptions = {}
): string {
  const title = normalizeTitle(options.title);
  const profiles = deriveContributorProfiles(values);
  const lines: string[] = [
    `# ${title}`,
    "",
    "<!-- Generated by Clarissimi from .clarissimi/contributions.jsonl. -->",
    ""
  ];

  if (profiles.length === 0) {
    lines.push("No approved recognition records yet.", "");
    return lines.join("\n");
  }

  profiles.forEach((profile) => {
    appendContributorProfile(lines, profile);
  });

  return lines.join("\n");
}

function appendContributorProfile(
  lines: string[],
  profile: ContributorRecognitionProfile
): void {
  lines.push(
    `## ${escapeMarkdown(profile.contributor.login)}`,
    "",
    renderContributionSummary(profile),
    ""
  );

  profile.recognitions.forEach((recognition) => {
    lines.push(`- ${renderRecognitionLine(recognition)}`);
  });

  lines.push("");
}

function renderContributionSummary(profile: ContributorRecognitionProfile): string {
  const contributionLabel = profile.contributionCount === 1
    ? "1 recognized contribution"
    : `${profile.contributionCount} recognized contributions`;
  const typeCounts = new Map<string, number>();

  profile.recognitions.forEach((recognition) => {
    typeCounts.set(
      recognition.contributionType,
      (typeCounts.get(recognition.contributionType) ?? 0) + 1
    );
  });

  const typeBreakdown = Array.from(typeCounts.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([type, count]) => `${escapeMarkdown(type)} ${count}`)
    .join(" · ");

  return `**${contributionLabel}** · ${typeBreakdown}`;
}

function renderRecognitionLine(recognition: PublicRecognitionSummary): string {
  const text = escapeMarkdown(recognition.publicRecognitionText);
  const badge = escapeMarkdown(recognition.suggestedBadge);
  const area = escapeMarkdown(recognition.affectedArea);
  const evidenceLink = firstEvidenceLink(recognition);

  if (evidenceLink === undefined) {
    return `${text} _${badge}_ in ${area}.`;
  }

  return `${text} _${badge}_ in ${area}. ${evidenceLink}`;
}

function firstEvidenceLink(recognition: PublicRecognitionSummary): string | undefined {
  const ref = recognition.evidenceRefs.find((candidate) => candidate.url !== undefined);
  if (ref === undefined || ref.url === undefined) {
    return undefined;
  }

  const label = ref.title ?? `${ref.kind} ${ref.id}`;
  return `[${escapeMarkdown(label)}](${ref.url})`;
}

function normalizeTitle(value: string | undefined): string {
  const normalized = value?.replace(/\s+/g, " ").trim();
  return normalized === undefined || normalized.length === 0 ? "Contributors" : normalized;
}

function escapeMarkdown(value: string): string {
  return value.replace(/([\\`*_{}[\]()#+.!|-])/g, "\\$1");
}
