import type { ConfigMarkdownSummary } from "@clarissimi/schemas";

import type { ContributorRecognitionProfile, PublicRecognitionSummary } from "./types.js";
import { deriveContributorProfiles } from "./contributors.js";
import type { ContributorDisplayOptions } from "./contributors.js";

const GALLERY_AVATAR_SIZE = 64;
const GALLERY_ROW_SIZE = 12;

export interface ContributorsMarkdownOptions extends ContributorDisplayOptions {
  readonly title?: string;
  readonly summary?: ConfigMarkdownSummary;
}

export function renderContributorsMarkdown(
  values: readonly unknown[],
  options: ContributorsMarkdownOptions = {},
): string {
  const title = normalizeTitle(options.title);
  const profiles = deriveContributorProfiles(values, options);
  const lines: string[] = [
    `# ${title}`,
    "",
    "<!-- Generated by Clarissimi from .clarissimi/contributions.jsonl. -->",
    "",
  ];

  if (profiles.length === 0) {
    lines.push("No approved recognition records yet.", "");
    return lines.join("\n");
  }

  if (options.summary === "table") {
    appendContributorSummaryTable(lines, profiles);
  }

  if (options.summary === "gallery") {
    appendContributorGallery(lines, profiles);
  }

  profiles.forEach((profile) => {
    appendContributorProfile(lines, profile);
  });

  return lines.join("\n");
}

function appendContributorGallery(
  lines: string[],
  profiles: readonly ContributorRecognitionProfile[],
): void {
  lines.push("## Contributor gallery", "");

  for (let offset = 0; offset < profiles.length; offset += GALLERY_ROW_SIZE) {
    lines.push(
      profiles
        .slice(offset, offset + GALLERY_ROW_SIZE)
        .map(renderGalleryAvatar)
        .join(" "),
    );
  }

  lines.push("");
}

function renderGalleryAvatar(profile: ContributorRecognitionProfile): string {
  const contributor = profile.contributor;
  const profileUrl = escapeHtmlAttribute(contributor.profileUrl);
  const avatarUrl = `https://avatars.githubusercontent.com/u/${encodeURIComponent(contributor.id)}?s=${GALLERY_AVATAR_SIZE}&v=4`;
  const alt = escapeHtmlAttribute(`@${contributor.login} on GitHub`);
  return `<a href="${profileUrl}"><img src="${avatarUrl}" width="${GALLERY_AVATAR_SIZE}" height="${GALLERY_AVATAR_SIZE}" alt="${alt}"></a>`;
}

function appendContributorSummaryTable(
  lines: string[],
  profiles: readonly ContributorRecognitionProfile[],
): void {
  lines.push("| Contributor | Total | Types |", "| --- | ---: | --- |");

  profiles.forEach((profile) => {
    const contributor = `[@${escapeMarkdown(profile.contributor.login)}](${profile.contributor.profileUrl})`;
    lines.push(
      `| ${contributor} | ${profile.contributionCount} | ${renderTypeBreakdown(profile)} |`,
    );
  });

  lines.push("");
}

function appendContributorProfile(lines: string[], profile: ContributorRecognitionProfile): void {
  const kindLabel = renderContributorKindLabel(profile.contributor.kind);
  lines.push(
    `## ${escapeMarkdown(profile.contributor.login)}${kindLabel}`,
    "",
    renderContributionSummary(profile),
    "",
  );

  profile.recognitions.forEach((recognition) => {
    lines.push(`- ${renderRecognitionLine(recognition)}`);
  });

  lines.push("");
}

function renderContributorKindLabel(
  kind: ContributorRecognitionProfile["contributor"]["kind"],
): string {
  if (kind === "bot") {
    return " · Bot";
  }

  if (kind === "ai_agent") {
    return " · AI agent";
  }

  return "";
}

function renderContributionSummary(profile: ContributorRecognitionProfile): string {
  const contributionLabel =
    profile.contributionCount === 1
      ? "1 recognized contribution"
      : `${profile.contributionCount} recognized contributions`;
  return `**${contributionLabel}** · ${renderTypeBreakdown(profile)}`;
}

function renderTypeBreakdown(profile: ContributorRecognitionProfile): string {
  const typeCounts = new Map<string, number>();

  profile.recognitions.forEach((recognition) => {
    typeCounts.set(
      recognition.contributionType,
      (typeCounts.get(recognition.contributionType) ?? 0) + 1,
    );
  });

  return Array.from(typeCounts.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([type, count]) => `${escapeMarkdown(type)} ${count}`)
    .join(" · ");
}

function renderRecognitionLine(recognition: PublicRecognitionSummary): string {
  const text = escapeMarkdown(recognition.publicRecognitionText);
  const badge = escapeMarkdown(recognition.suggestedBadge);
  const area = escapeMarkdown(recognition.affectedArea);
  const evidenceLink = firstEvidenceLink(recognition);

  if (evidenceLink === undefined) {
    return `${text} _${badge}_ in ${area}.`;
  }

  return `${text} _${badge}_ in ${area}. ${evidenceLink}`;
}

function firstEvidenceLink(recognition: PublicRecognitionSummary): string | undefined {
  const ref = recognition.evidenceRefs.find((candidate) => candidate.url !== undefined);
  if (ref === undefined || ref.url === undefined) {
    return undefined;
  }

  const label = ref.title ?? `${ref.kind} ${ref.id}`;
  return `[${escapeMarkdown(label)}](${ref.url})`;
}

function normalizeTitle(value: string | undefined): string {
  const normalized = value?.replace(/\s+/g, " ").trim();
  return normalized === undefined || normalized.length === 0 ? "Contributors" : normalized;
}

function escapeMarkdown(value: string): string {
  return value.replace(/([\\`*_{}[\]()#+.!|-])/g, "\\$1");
}

function escapeHtmlAttribute(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}
